name: intermap-dev
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - ipython
  - pytest
  - pytest-cov
  - matplotlib
  - mdtraj
  - mdanalysis
  - rdkit
  - numpy
  - bitarray ~= 3.0.0
  - numba ~= 0.61.0
  - pip
  - pip:
      - -e .
      - memory_profiler
      - numpy_indexed
      - numba_kdtree == 0.5.0
      - pytest-randomly
      - openpyxl
      - git+https://github.com/rglez/rgpack.git@0.0.3
